name: UniversalStandardAdapter
version: 0.0.2
main: de.xzise.usa.UniversalStandardAdapter
authors:
  - 'xZise'
commands:
  usa:
    description: Universal Standard Adapter commands
    usage: /<command> <name> - Show the registered plugin for the name.
